{"dependencies":[{"name":"util","loc":{"line":2,"column":19}},{"name":"events","loc":{"line":3,"column":27}},{"name":"process"}],"generated":{"js":"var process = require(\"process\");\n'use strict';\nvar util = require('util');\nvar EventEmitter = require('events').EventEmitter;\nfunction toArray(arr, start, end) {\n  return Array.prototype.slice.call(arr, start, end)\n}\nfunction strongUnshift(x, arrLike) {\n  var arr = toArray(arrLike);\n  arr.unshift(x);\n  return arr;\n}\n\n\n/**\n * MPromise constructor.\n *\n * _NOTE: The success and failure event names can be overridden by setting `Promise.SUCCESS` and `Promise.FAILURE` respectively._\n *\n * @param {Function} back a function that accepts `fn(err, ...){}` as signature\n * @inherits NodeJS EventEmitter http://nodejs.org/api/events.html#events_class_events_eventemitter\n * @event `reject`: Emits when the promise is rejected (event name may be overridden)\n * @event `fulfill`: Emits when the promise is fulfilled (event name may be overridden)\n * @api public\n */\nfunction Promise(back) {\n  this.emitter = new EventEmitter();\n  this.emitted = {};\n  this.ended = false;\n  if ('function' == typeof back) {\n    this.ended = true;\n    this.onResolve(back);\n  }\n}\n\n\n/*\n * Module exports.\n */\nmodule.exports = Promise;\n\n\n/*!\n * event names\n */\nPromise.SUCCESS = 'fulfill';\nPromise.FAILURE = 'reject';\n\n\n/**\n * Adds `listener` to the `event`.\n *\n * If `event` is either the success or failure event and the event has already been emitted, the`listener` is called immediately and passed the results of the original emitted event.\n *\n * @param {String} event\n * @param {Function} callback\n * @return {MPromise} this\n * @api private\n */\nPromise.prototype.on = function (event, callback) {\n  if (this.emitted[event])\n    callback.apply(undefined, this.emitted[event]);\n  else\n    this.emitter.on(event, callback);\n\n  return this;\n};\n\n\n/**\n * Keeps track of emitted events to run them on `on`.\n *\n * @api private\n */\nPromise.prototype.safeEmit = function (event) {\n  // ensures a promise can't be fulfill() or reject() more than once\n  if (event == Promise.SUCCESS || event == Promise.FAILURE) {\n    if (this.emitted[Promise.SUCCESS] || this.emitted[Promise.FAILURE]) {\n      return this;\n    }\n    this.emitted[event] = toArray(arguments, 1);\n  }\n\n  this.emitter.emit.apply(this.emitter, arguments);\n  return this;\n};\n\n\n/**\n * @api private\n */\nPromise.prototype.hasRejectListeners = function () {\n  return EventEmitter.listenerCount(this.emitter, Promise.FAILURE) > 0;\n};\n\n\n/**\n * Fulfills this promise with passed arguments.\n *\n * If this promise has already been fulfilled or rejected, no action is taken.\n *\n * @api public\n */\nPromise.prototype.fulfill = function () {\n  return this.safeEmit.apply(this, strongUnshift(Promise.SUCCESS, arguments));\n};\n\n\n/**\n * Rejects this promise with `reason`.\n *\n * If this promise has already been fulfilled or rejected, no action is taken.\n *\n * @api public\n * @param {Object|String} reason\n * @return {MPromise} this\n */\nPromise.prototype.reject = function (reason) {\n  if (this.ended && !this.hasRejectListeners())\n    throw reason;\n  return this.safeEmit(Promise.FAILURE, reason);\n};\n\n\n/**\n * Resolves this promise to a rejected state if `err` is passed or\n * fulfilled state if no `err` is passed.\n *\n * @param {Error} [err] error or null\n * @param {Object} [val] value to fulfill the promise with\n * @api public\n */\nPromise.prototype.resolve = function (err, val) {\n  if (err) return this.reject(err);\n  return this.fulfill(val);\n};\n\n\n/**\n * Adds a listener to the SUCCESS event.\n *\n * @return {MPromise} this\n * @api public\n */\nPromise.prototype.onFulfill = function (fn) {\n  if (!fn) return this;\n  if ('function' != typeof fn) throw new TypeError(\"fn should be a function\");\n  return this.on(Promise.SUCCESS, fn);\n};\n\n\n/**\n * Adds a listener to the FAILURE event.\n *\n * @return {MPromise} this\n * @api public\n */\nPromise.prototype.onReject = function (fn) {\n  if (!fn) return this;\n  if ('function' != typeof fn) throw new TypeError(\"fn should be a function\");\n  return this.on(Promise.FAILURE, fn);\n};\n\n\n/**\n * Adds a single function as a listener to both SUCCESS and FAILURE.\n *\n * It will be executed with traditional node.js argument position:\n * function (err, args...) {}\n *\n * Also marks the promise as `end`ed, since it's the common use-case, and yet has no\n * side effects unless `fn` is undefined or null.\n *\n * @param {Function} fn\n * @return {MPromise} this\n */\nPromise.prototype.onResolve = function (fn) {\n  if (!fn) return this;\n  if ('function' != typeof fn) throw new TypeError(\"fn should be a function\");\n  this.on(Promise.FAILURE, function (err) { fn.call(this, err); });\n  this.on(Promise.SUCCESS, function () { fn.apply(this, strongUnshift(null, arguments)); });\n  return this;\n};\n\n\n/**\n * Creates a new promise and returns it. If `onFulfill` or\n * `onReject` are passed, they are added as SUCCESS/ERROR callbacks\n * to this promise after the next tick.\n *\n * Conforms to [promises/A+](https://github.com/promises-aplus/promises-spec) specification. Read for more detail how to use this method.\n *\n * ####Example:\n *\n *     var p = new Promise;\n *     p.then(function (arg) {\n *       return arg + 1;\n *     }).then(function (arg) {\n *       throw new Error(arg + ' is an error!');\n *     }).then(null, function (err) {\n *       assert.ok(err instanceof Error);\n *       assert.equal('2 is an error', err.message);\n *     });\n *     p.complete(1);\n *\n * @see promises-A+ https://github.com/promises-aplus/promises-spec\n * @param {Function} onFulfill\n * @param {Function} [onReject]\n * @return {MPromise} newPromise\n */\nPromise.prototype.then = function (onFulfill, onReject) {\n  var newPromise = new Promise;\n\n  if ('function' == typeof onFulfill) {\n    this.onFulfill(handler(newPromise, onFulfill));\n  } else {\n    this.onFulfill(newPromise.fulfill.bind(newPromise));\n  }\n\n  if ('function' == typeof onReject) {\n    this.onReject(handler(newPromise, onReject));\n  } else {\n    this.onReject(newPromise.reject.bind(newPromise));\n  }\n\n  return newPromise;\n};\n\n\nfunction handler(promise, fn) {\n  function newTickHandler() {\n    var pDomain = promise.emitter.domain;\n    if (pDomain && pDomain !== process.domain) pDomain.enter();\n    try {\n      var x = fn.apply(undefined, boundHandler.args);\n    } catch (err) {\n      promise.reject(err);\n      return;\n    }\n    resolve(promise, x);\n  }\n  function boundHandler() {\n    boundHandler.args = arguments;\n    process.nextTick(newTickHandler);\n  }\n  return boundHandler;\n}\n\n\nfunction resolve(promise, x) {\n  function fulfillOnce() {\n    if (done++) return;\n    resolve.apply(undefined, strongUnshift(promise, arguments));\n  }\n  function rejectOnce(reason) {\n    if (done++) return;\n    promise.reject(reason);\n  }\n\n  if (promise === x) {\n    promise.reject(new TypeError(\"promise and x are the same\"));\n    return;\n  }\n  var rest = toArray(arguments, 1);\n  var type = typeof x;\n  if ('undefined' == type || null == x || !('object' == type || 'function' == type)) {\n    promise.fulfill.apply(promise, rest);\n    return;\n  }\n\n  try {\n    var theThen = x.then;\n  } catch (err) {\n    promise.reject(err);\n    return;\n  }\n\n  if ('function' != typeof theThen) {\n    promise.fulfill.apply(promise, rest);\n    return;\n  }\n\n  var done = 0;\n  try {\n    var ret = theThen.call(x, fulfillOnce, rejectOnce);\n    return ret;\n  } catch (err) {\n    if (done++) return;\n    promise.reject(err);\n  }\n}\n\n\n/**\n * Signifies that this promise was the last in a chain of `then()s`: if a handler passed to the call to `then` which produced this promise throws, the exception will go uncaught.\n *\n * ####Example:\n *\n *     var p = new Promise;\n *     p.then(function(){ throw new Error('shucks') });\n *     setTimeout(function () {\n *       p.fulfill();\n *       // error was caught and swallowed by the promise returned from\n *       // p.then(). we either have to always register handlers on\n *       // the returned promises or we can do the following...\n *     }, 10);\n *\n *     // this time we use .end() which prevents catching thrown errors\n *     var p = new Promise;\n *     var p2 = p.then(function(){ throw new Error('shucks') }).end(); // <--\n *     setTimeout(function () {\n *       p.fulfill(); // throws \"shucks\"\n *     }, 10);\n *\n * @api public\n * @param {Function} [onReject]\n * @return {MPromise} this\n */\nPromise.prototype.end = Promise.prototype['catch'] = function (onReject) {\n  if (!onReject && !this.hasRejectListeners())\n    onReject = function idRejector(e) { throw e; };\n  this.onReject(onReject);\n  this.ended = true;\n  return this;\n};\n\n\n/**\n * A debug utility function that adds handlers to a promise that will log some output to the `console`\n *\n * ####Example:\n *\n *     var p = new Promise;\n *     p.then(function(){ throw new Error('shucks') });\n *     setTimeout(function () {\n *       p.fulfill();\n *       // error was caught and swallowed by the promise returned from\n *       // p.then(). we either have to always register handlers on\n *       // the returned promises or we can do the following...\n *     }, 10);\n *\n *     // this time we use .end() which prevents catching thrown errors\n *     var p = new Promise;\n *     var p2 = p.then(function(){ throw new Error('shucks') }).end(); // <--\n *     setTimeout(function () {\n *       p.fulfill(); // throws \"shucks\"\n *     }, 10);\n *\n * @api public\n * @param {MPromise} p\n * @param {String} name\n * @return {MPromise} this\n */\nPromise.trace = function (p, name) {\n  p.then(\n    function () {\n      console.log(\"%s fulfill %j\", name, toArray(arguments));\n    },\n    function () {\n      console.log(\"%s reject %j\", name, toArray(arguments));\n    }\n  )\n};\n\n\nPromise.prototype.chain = function (p2) {\n  var p1 = this;\n  p1.onFulfill(p2.fulfill.bind(p2));\n  p1.onReject(p2.reject.bind(p2));\n  return p2;\n};\n\n\nPromise.prototype.all = function (promiseOfArr) {\n  var pRet = new Promise;\n  this.then(promiseOfArr).then(\n    function (promiseArr) {\n      var count = 0;\n      var ret = [];\n      var errSentinel;\n      if (!promiseArr.length) pRet.resolve();\n      promiseArr.forEach(function (promise, index) {\n        if (errSentinel) return;\n        count++;\n        promise.then(\n          function (val) {\n            if (errSentinel) return;\n            ret[index] = val;\n            --count;\n            if (count == 0) pRet.fulfill(ret);\n          },\n          function (err) {\n            if (errSentinel) return;\n            errSentinel = err;\n            pRet.reject(err);\n          }\n        );\n      });\n      return pRet;\n    }\n    , pRet.reject.bind(pRet)\n  );\n  return pRet;\n};\n\n\nPromise.hook = function (arr) {\n  var p1 = new Promise;\n  var pFinal = new Promise;\n  var signalP = function () {\n    --count;\n    if (count == 0)\n      pFinal.fulfill();\n    return pFinal;\n  };\n  var count = 1;\n  var ps = p1;\n  arr.forEach(function (hook) {\n    ps = ps.then(\n      function () {\n        var p = new Promise;\n        count++;\n        hook(p.resolve.bind(p), signalP);\n        return p;\n      }\n    )\n  });\n  ps = ps.then(signalP);\n  p1.resolve();\n  return ps;\n};\n\n\n/* This is for the A+ tests, but it's very useful as well */\nPromise.fulfilled = function fulfilled() { var p = new Promise; p.fulfill.apply(p, arguments); return p; };\nPromise.rejected = function rejected(reason) { return new Promise().reject(reason); };\nPromise.deferred = function deferred() {\n  var p = new Promise;\n  return {\n    promise: p,\n    reject: p.reject.bind(p),\n    resolve: p.fulfill.bind(p),\n    callback: p.resolve.bind(p)\n  }\n};\n/* End A+ tests adapter bit */\n"},"hash":"d1124f99ac922f33c124cd693b55151f"}